/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.View;

import edu.neu.csye6200.Controller.DataStore;
import java.awt.CardLayout;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chenyu
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    private JPanel userProcessContainer;
    private DataStore dataStore;

    public LoginPanel() {
        initComponents();
    }

    public LoginPanel(JPanel userProcessContainer, DataStore dataStore) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.dataStore = dataStore; //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPIN = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btnLogIn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnStudentView = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUNAME = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setLayout(null);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setText("Quick View:");
        add(jLabel7);
        jLabel7.setBounds(220, 410, 170, 22);

        txtPIN.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        txtPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPINActionPerformed(evt);
            }
        });
        txtPIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPINKeyTyped(evt);
            }
        });
        add(txtPIN);
        txtPIN.setBounds(350, 230, 291, 32);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Password:");
        add(jLabel3);
        jLabel3.setBounds(220, 230, 93, 22);

        btnLogIn.setText("Teacher Login");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        add(btnLogIn);
        btnLogIn.setBounds(370, 290, 132, 30);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel8.setText("Or");
        add(jLabel8);
        jLabel8.setBounds(420, 360, 97, 22);

        btnStudentView.setText("Student View");
        btnStudentView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentViewActionPerformed(evt);
            }
        });
        add(btnStudentView);
        btnStudentView.setBounds(530, 410, 132, 29);

        jButton1.setText("Teacher View");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(380, 410, 132, 29);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 100));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("Login Page");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(76, 40, 102, 22);

        add(jPanel2);
        jPanel2.setBounds(0, 0, 900, 100);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel4.setText("Username:");
        add(jLabel4);
        jLabel4.setBounds(220, 160, 97, 22);

        txtUNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUNAMEActionPerformed(evt);
            }
        });
        add(txtUNAME);
        txtUNAME.setBounds(350, 160, 291, 26);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/neu/csye6200/View/icon/back.jpg"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 96, 1000, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPINKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPINKeyTyped

    }//GEN-LAST:event_txtPINKeyTyped

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        String username = "admin";
        String s = "123456";
        if (!username.equals(txtUNAME.getText())) {
            JOptionPane.showMessageDialog(null, "Please input the valid username!");
            return;
        }
        if (Arrays.equals(txtPIN.getPassword(), s.toCharArray())) {
            JOptionPane.showMessageDialog(null, "Log in successfully!");
            txtPIN.setText("");
            ManageJPanel panel = new ManageJPanel(userProcessContainer, dataStore);
            userProcessContainer.add("ManageJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(null, "Please input the right password!");
        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnStudentViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentViewActionPerformed
        StudentViewPanel panel = new StudentViewPanel(userProcessContainer, dataStore);
        userProcessContainer.add("studentViewJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentViewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TeacherViewPanel panel = new TeacherViewPanel(userProcessContainer, dataStore);
        userProcessContainer.add("teacherViewJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUNAMEActionPerformed

    private void txtPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPINActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnStudentView;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtPIN;
    private javax.swing.JTextField txtUNAME;
    // End of variables declaration//GEN-END:variables
}
