/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.View;

import edu.neu.csye6200.Controller.DataStore;
import edu.neu.csye6200.Controller.FileUtil;
import edu.neu.csye6200.Controller.RatioRule;
import edu.neu.csye6200.Object.Student;
import edu.neu.csye6200.Object.Teacher;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Yining Chen
 */
public class StudentChangePanel extends javax.swing.JPanel {

    /**
     * Creates new form TeacherRegisterPanel
     */
    private JPanel userProcessContainer;
    private DataStore dataStore;
    private Student student;

    public StudentChangePanel() {

    }

    public StudentChangePanel(JPanel userProcessContainer, DataStore dataStore, Student student) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.dataStore = dataStore;
        this.student = student;
        int stuId = student.getStuID();
        txtID.setText(stuId + "");
        txtID.setEditable(false);

        populateInputs();

    }

    private void populateInputs() {
        txtFname.setText(student.getFirstName());
        txtLname.setText(student.getLastName());
        txtAge.setText(Integer.toString(student.getAge()));
        txtPnumber.setText(student.getPhoneNumber());
        txtAddress.setText(student.getAddress());
        txtPfname.setText(student.getParentFirstName());
        txtPlame.setText(student.getParentLastName());
        txtbirthday.setText(student.getBirthday());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPnumber = new javax.swing.JTextField();
        txtPfname = new javax.swing.JTextField();
        txtPlame = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtbirthday = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 100));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Student Information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1)
                .addContainerGap(603, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 100);

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn);
        updateBtn.setBounds(320, 500, 88, 38);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn);
        saveBtn.setBounds(440, 500, 88, 41);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 17)); // NOI18N
        jLabel10.setText("Personal Information");
        add(jLabel10);
        jLabel10.setBounds(336, 100, 186, 21);

        jLabel2.setText("Student ID:");
        add(jLabel2);
        jLabel2.setBounds(336, 144, 70, 16);

        jLabel3.setText("First Name:");
        add(jLabel3);
        jLabel3.setBounds(338, 182, 72, 16);

        jLabel4.setText("Last Name:");
        add(jLabel4);
        jLabel4.setBounds(338, 221, 70, 16);

        jLabel7.setText("Age:");
        add(jLabel7);
        jLabel7.setBounds(338, 258, 28, 16);

        jLabel8.setText("Address:");
        add(jLabel8);
        jLabel8.setBounds(338, 296, 55, 16);

        jLabel9.setText("Phone Number:");
        add(jLabel9);
        jLabel9.setBounds(335, 341, 96, 16);

        jLabel5.setText("Parent First Name:");
        add(jLabel5);
        jLabel5.setBounds(329, 385, 115, 16);

        jLabel6.setText("Parent Last Name:");
        add(jLabel6);
        jLabel6.setBounds(329, 429, 113, 16);

        txtID.setEnabled(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        add(txtID);
        txtID.setBounds(459, 139, 109, 26);

        txtFname.setEnabled(false);
        add(txtFname);
        txtFname.setBounds(459, 177, 109, 26);

        txtLname.setEnabled(false);
        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        add(txtLname);
        txtLname.setBounds(459, 215, 109, 26);

        txtAge.setEnabled(false);
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge);
        txtAge.setBounds(459, 253, 109, 26);

        txtAddress.setEnabled(false);
        add(txtAddress);
        txtAddress.setBounds(459, 291, 109, 26);

        txtPnumber.setEnabled(false);
        add(txtPnumber);
        txtPnumber.setBounds(459, 336, 109, 26);

        txtPfname.setEnabled(false);
        add(txtPfname);
        txtPfname.setBounds(462, 380, 109, 26);

        txtPlame.setEnabled(false);
        add(txtPlame);
        txtPlame.setBounds(462, 424, 109, 26);

        jLabel11.setText("Birthday:");
        add(jLabel11);
        jLabel11.setBounds(330, 462, 55, 16);

        txtbirthday.setEnabled(false);
        add(txtbirthday);
        txtbirthday.setBounds(450, 460, 120, 26);

        registerBtn.setText("Register again");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        add(registerBtn);
        registerBtn.setBounds(610, 180, 125, 41);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/neu/csye6200/View/icon/back.jpg"))); // NOI18N
        add(jLabel12);
        jLabel12.setBounds(0, 96, 900, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        txtFname.setEnabled(true);
        txtLname.setEnabled(true);
        txtAge.setEnabled(true);
        txtPnumber.setEnabled(true);
        txtAddress.setEnabled(true);
        txtPfname.setEnabled(true);
        txtPlame.setEnabled(true);
        txtbirthday.setEnabled(true);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        RatioRule.techTogroup(dataStore.getTchList(), dataStore);

        if (txtFname.getText().equals("") | txtLname.getText().equals("") | txtAge.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Student's information can not be empty");
            return;
        }

        try {
            Integer.parseInt(txtAge.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Student's age can not be letters");
            return;
        }

        //int tchId 
        String Fname = txtFname.getText();
        String Lname = txtLname.getText();
        String Address = txtAddress.getText();
        String Age = txtAge.getText();
        String Pnumber = txtPnumber.getText();
        String Pfname = txtPfname.getText();
        String Plname = txtPlame.getText();
        String Birthday = txtbirthday.getText();

        student.setFirstName(Fname);
        student.setLastName(Lname);
        student.setPhoneNumber(Pnumber);
        student.setAddress(Address);
        student.setAge(Integer.parseInt(Age));
        student.setParentFirstName(Pfname);
        student.setPhoneNumber(Pnumber);
        student.setParentLastName(Plname);
        student.setBirthday(Birthday);
        FileUtil.writeCsv();

        String success = "Change successfully!";
        txtFname.setEnabled(false);
        txtLname.setEnabled(false);
        txtAge.setEnabled(false);
        txtPnumber.setEnabled(false);
        txtAddress.setEnabled(false);
        txtPfname.setEnabled(false);
        txtPfname.setEnabled(false);
        txtbirthday.setEnabled(false);

        JOptionPane.showMessageDialog(null, success);
        toStudentInfoScreen();

    }//GEN-LAST:event_saveBtnActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        student.setRegisterState(true);
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("M/dd/yyyy");
        String registerdate = dateFormat.format(date);
        student.setRegisterDate(registerdate);
        FileUtil.writeCsv();
        String success = "Re-registration is successful!";
        JOptionPane.showMessageDialog(null, success);
        toStudentInfoScreen();
    }//GEN-LAST:event_registerBtnActionPerformed
    private void toStudentInfoScreen() {
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        this.userProcessContainer.remove(this);
        Component[] comps = this.userProcessContainer.getComponents();
        for (Component comp : comps) {
            if (comp instanceof StudentManagementPanel) {
                StudentManagementPanel panel = (StudentManagementPanel) comp;
                panel.populate();
            }
        }
        layout.previous(userProcessContainer);
    }

    private int getMaxTchId(List<Teacher> list) {
        int maxID = list.get(list.size() - 1).getTeacherID();
        return maxID;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPfname;
    private javax.swing.JTextField txtPlame;
    private javax.swing.JTextField txtPnumber;
    private javax.swing.JTextField txtbirthday;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
