/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.neu.csye6200.View;

import edu.neu.csye6200.Controller.DataStore;
import edu.neu.csye6200.Controller.FileUtil;
import edu.neu.csye6200.Controller.RatioRule;
import edu.neu.csye6200.Object.Student;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author chenyu
 */
public class StudentRegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentRegisterPanel
     */
    private JPanel userProcessContainer;
    private DataStore dataStore;

    public StudentRegisterPanel() {

    }

    public StudentRegisterPanel(JPanel userProcessContainer, DataStore dataStore) {
        initComponents(); //To change body of generated methods, choose Tools | Templates.
        this.userProcessContainer = userProcessContainer;
        this.dataStore = dataStore;
        int stuId = getMaxStuId(dataStore.getStuList()) + 1;
        txtID.setText(stuId + "");
        txtID.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtPnumber = new javax.swing.JTextField();
        txtPfname = new javax.swing.JTextField();
        txtPlame = new javax.swing.JTextField();
        txtHepb1 = new javax.swing.JTextField();
        txtHepb2 = new javax.swing.JTextField();
        txtHepb3 = new javax.swing.JTextField();
        txtHepb5 = new javax.swing.JTextField();
        txtHepb4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtHib1 = new javax.swing.JTextField();
        txtDTap2 = new javax.swing.JTextField();
        txtDTap3 = new javax.swing.JTextField();
        txtDTap4 = new javax.swing.JTextField();
        txtDTap5 = new javax.swing.JTextField();
        txtHib5 = new javax.swing.JTextField();
        txtHib4 = new javax.swing.JTextField();
        txtHib3 = new javax.swing.JTextField();
        txtHib2 = new javax.swing.JTextField();
        txtDTap1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtMMR1 = new javax.swing.JTextField();
        txtMMR2 = new javax.swing.JTextField();
        txtMMR3 = new javax.swing.JTextField();
        txtMMR4 = new javax.swing.JTextField();
        txtMMR5 = new javax.swing.JTextField();
        txtIPV5 = new javax.swing.JTextField();
        txtIPV4 = new javax.swing.JTextField();
        txtIPV3 = new javax.swing.JTextField();
        txtIPV2 = new javax.swing.JTextField();
        txtIPV1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtVAR1 = new javax.swing.JTextField();
        txtVAR3 = new javax.swing.JTextField();
        txtVAR2 = new javax.swing.JTextField();
        txtVAR4 = new javax.swing.JTextField();
        txtVAR5 = new javax.swing.JTextField();
        txtMein5 = new javax.swing.JTextField();
        txtMein4 = new javax.swing.JTextField();
        txtMein3 = new javax.swing.JTextField();
        txtMein2 = new javax.swing.JTextField();
        txtMein1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtbirthday = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 17)); // NOI18N
        jLabel10.setText("Personal Information");
        add(jLabel10);
        jLabel10.setBounds(39, 137, 186, 21);

        jLabel2.setText("Student ID:");
        add(jLabel2);
        jLabel2.setBounds(39, 181, 70, 16);

        jLabel3.setText("First Name:");
        add(jLabel3);
        jLabel3.setBounds(41, 219, 72, 16);

        jLabel4.setText("Last Name:");
        add(jLabel4);
        jLabel4.setBounds(41, 258, 70, 16);

        jLabel7.setText("Age:");
        add(jLabel7);
        jLabel7.setBounds(41, 295, 28, 16);

        jLabel8.setText("Address:");
        add(jLabel8);
        jLabel8.setBounds(41, 333, 55, 16);

        jLabel9.setText("Phone Number:");
        add(jLabel9);
        jLabel9.setBounds(38, 378, 96, 16);

        jLabel5.setText("Parent First Name:");
        add(jLabel5);
        jLabel5.setBounds(32, 422, 115, 16);

        jLabel6.setText("Parent Last Name:");
        add(jLabel6);
        jLabel6.setBounds(32, 466, 113, 16);

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        add(txtID);
        txtID.setBounds(162, 176, 109, 26);
        add(txtFname);
        txtFname.setBounds(162, 214, 109, 26);

        txtLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLnameActionPerformed(evt);
            }
        });
        add(txtLname);
        txtLname.setBounds(162, 252, 109, 26);

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        add(txtAge);
        txtAge.setBounds(162, 290, 109, 26);
        add(txtAddress);
        txtAddress.setBounds(162, 328, 109, 26);
        add(txtPnumber);
        txtPnumber.setBounds(162, 373, 109, 26);
        add(txtPfname);
        txtPfname.setBounds(165, 417, 109, 26);
        add(txtPlame);
        txtPlame.setBounds(165, 461, 109, 26);

        txtHepb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHepb1ActionPerformed(evt);
            }
        });
        add(txtHepb1);
        txtHepb1.setBounds(430, 210, 60, 26);
        add(txtHepb2);
        txtHepb2.setBounds(520, 210, 60, 26);

        txtHepb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHepb3ActionPerformed(evt);
            }
        });
        add(txtHepb3);
        txtHepb3.setBounds(609, 209, 60, 26);
        add(txtHepb5);
        txtHepb5.setBounds(794, 209, 60, 26);
        add(txtHepb4);
        txtHepb4.setBounds(700, 209, 60, 26);

        jLabel19.setText("Dozen1");
        add(jLabel19);
        jLabel19.setBounds(430, 190, 48, 16);

        jLabel20.setText("Dozen2");
        add(jLabel20);
        jLabel20.setBounds(520, 190, 48, 16);

        jLabel21.setText("Dozen3");
        add(jLabel21);
        jLabel21.setBounds(610, 190, 48, 16);

        jLabel22.setText("Dozen4");
        add(jLabel22);
        jLabel22.setBounds(700, 190, 48, 16);

        jLabel23.setText("Dozen5");
        add(jLabel23);
        jLabel23.setBounds(800, 190, 48, 16);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 17)); // NOI18N
        jLabel11.setText("Immunization Record");
        add(jLabel11);
        jLabel11.setBounds(331, 137, 188, 21);
        add(txtHib1);
        txtHib1.setBounds(430, 340, 60, 26);
        add(txtDTap2);
        txtDTap2.setBounds(520, 250, 60, 26);
        add(txtDTap3);
        txtDTap3.setBounds(609, 253, 60, 26);
        add(txtDTap4);
        txtDTap4.setBounds(700, 253, 60, 26);
        add(txtDTap5);
        txtDTap5.setBounds(794, 253, 60, 26);
        add(txtHib5);
        txtHib5.setBounds(794, 297, 60, 26);

        txtHib4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHib4ActionPerformed(evt);
            }
        });
        add(txtHib4);
        txtHib4.setBounds(700, 297, 60, 26);
        add(txtHib3);
        txtHib3.setBounds(610, 300, 60, 26);
        add(txtHib2);
        txtHib2.setBounds(520, 300, 60, 26);

        txtDTap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDTap1ActionPerformed(evt);
            }
        });
        add(txtDTap1);
        txtDTap1.setBounds(430, 250, 60, 26);

        jLabel14.setText("Hib");
        add(jLabel14);
        jLabel14.setBounds(332, 302, 22, 16);

        jLabel13.setText("DTaP");
        add(jLabel13);
        jLabel13.setBounds(332, 258, 32, 16);

        jLabel12.setText("Hepb");
        add(jLabel12);
        jLabel12.setBounds(331, 214, 33, 16);

        jLabel15.setText("MMR");
        add(jLabel15);
        jLabel15.setBounds(332, 341, 30, 16);
        add(txtMMR1);
        txtMMR1.setBounds(430, 390, 60, 26);

        txtMMR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMMR2ActionPerformed(evt);
            }
        });
        add(txtMMR2);
        txtMMR2.setBounds(520, 340, 59, 26);
        add(txtMMR3);
        txtMMR3.setBounds(610, 340, 60, 26);
        add(txtMMR4);
        txtMMR4.setBounds(700, 341, 60, 26);

        txtMMR5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMMR5ActionPerformed(evt);
            }
        });
        add(txtMMR5);
        txtMMR5.setBounds(794, 341, 60, 26);

        txtIPV5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPV5ActionPerformed(evt);
            }
        });
        add(txtIPV5);
        txtIPV5.setBounds(790, 390, 60, 26);
        add(txtIPV4);
        txtIPV4.setBounds(700, 390, 60, 26);

        txtIPV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPV3ActionPerformed(evt);
            }
        });
        add(txtIPV3);
        txtIPV3.setBounds(610, 390, 60, 26);

        txtIPV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPV2ActionPerformed(evt);
            }
        });
        add(txtIPV2);
        txtIPV2.setBounds(520, 390, 60, 26);
        add(txtIPV1);
        txtIPV1.setBounds(430, 430, 60, 26);

        jLabel16.setText("IPV");
        add(jLabel16);
        jLabel16.setBounds(332, 386, 19, 16);

        jLabel17.setText("VAR");
        add(jLabel17);
        jLabel17.setBounds(332, 434, 25, 16);
        add(txtVAR1);
        txtVAR1.setBounds(430, 300, 60, 26);
        add(txtVAR3);
        txtVAR3.setBounds(610, 430, 60, 26);
        add(txtVAR2);
        txtVAR2.setBounds(520, 430, 60, 26);
        add(txtVAR4);
        txtVAR4.setBounds(700, 430, 60, 26);
        add(txtVAR5);
        txtVAR5.setBounds(794, 429, 60, 26);
        add(txtMein5);
        txtMein5.setBounds(790, 480, 60, 26);
        add(txtMein4);
        txtMein4.setBounds(700, 480, 60, 26);

        txtMein3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMein3ActionPerformed(evt);
            }
        });
        add(txtMein3);
        txtMein3.setBounds(610, 480, 60, 26);
        add(txtMein2);
        txtMein2.setBounds(520, 480, 60, 26);

        txtMein1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMein1ActionPerformed(evt);
            }
        });
        add(txtMein1);
        txtMein1.setBounds(430, 480, 58, 26);

        jLabel18.setText("Meningococcal");
        add(jLabel18);
        jLabel18.setBounds(330, 480, 94, 16);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(687, 517, 95, 29);

        jButton2.setText("<< Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(32, 553, 97, 29);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("New Student Register");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(568, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38))
        );

        add(jPanel1);
        jPanel1.setBounds(0, 0, 863, 100);

        jLabel24.setText("Birthday");
        add(jLabel24);
        jLabel24.setBounds(32, 504, 51, 16);
        add(txtbirthday);
        txtbirthday.setBounds(165, 499, 109, 26);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/neu/csye6200/View/icon/back.jpg"))); // NOI18N
        add(jLabel25);
        jLabel25.setBounds(0, 96, 1000, 610);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLnameActionPerformed

    private void txtHepb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHepb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHepb3ActionPerformed

    private void txtHib4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHib4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHib4ActionPerformed

    private void txtMMR5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMMR5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMMR5ActionPerformed

    private void txtMMR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMMR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMMR2ActionPerformed

    private void txtIPV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPV2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPV2ActionPerformed

    private void txtIPV5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPV5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPV5ActionPerformed

    private void txtMein3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMein3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMein3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        if (txtAge.getText().equals("") | txtFname.getText().equals("") | txtLname.getText().equals("") | txtPfname.getText().equals("") | txtPlame.getText().equals("") | txtAddress.getText().equals("") | txtPnumber.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Personal information can not be empty");
            return;
        }
        try {
            Integer.parseInt(txtAge.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Student's age can not be letters");
            return;
        }
        //int stuId = Integer.parseInt(getMaxStuId(dataStore.getStuList())) + 1;
        int stuAge = Integer.parseInt(txtAge.getText());
        //int stuId=Integer.parseInt(txtID.getText());
        int stuId = getMaxStuId(dataStore.getStuList()) + 1;
        String stuFname = txtFname.getText();
        String stuLname = txtLname.getText();
        String parentFname = txtPfname.getText();
        String parentLname = txtPlame.getText();
        String address = txtAddress.getText();
        String teleNumber = txtPnumber.getText();
        String birthday = txtbirthday.getText();
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("M/dd/yyyy");
        String registerdate = dateFormat.format(date);

        String[] arrayHebp = {txtHepb1.getText(), txtHepb2.getText(), txtHepb3.getText(), txtHepb4.getText(), txtHepb5.getText()};
        String[] arrayDTaP = {txtDTap1.getText(), txtDTap2.getText(), txtDTap3.getText(), txtDTap4.getText(), txtDTap5.getText()};
        String[] arrayHib = {txtHib1.getText(), txtHib2.getText(), txtHib3.getText(), txtHib4.getText(), txtHib5.getText()};
        String[] arrayMMR = {txtMMR1.getText(), txtMMR2.getText(), txtMMR3.getText(), txtMMR4.getText(), txtMMR5.getText()};
        String[] arrayIPV = {txtIPV1.getText(), txtIPV2.getText(), txtIPV3.getText(), txtIPV4.getText(), txtIPV5.getText()};
        String[] arrayVAR = {txtVAR1.getText(), txtVAR2.getText(), txtVAR3.getText(), txtVAR4.getText(), txtVAR5.getText()};
        String[] arrayMeningococcal = {txtMein1.getText(), txtMein2.getText(), txtMein3.getText(), txtMein4.getText(), txtMein5.getText()};
        Student stu = new Student(stuId, stuAge, stuFname, stuLname, parentFname, parentLname, address, teleNumber, birthday);
        stu.setRegisterDate(registerdate);
        //   stu.setImmunizationmap(dataStore.getImmuList());
        stu.getImmunizationmap().get("Hepatitis B").setDate(arrayHebp);
        stu.getImmunizationmap().get("Dtap").setDate(arrayDTaP);
        stu.getImmunizationmap().get("Hib").setDate(arrayHib);
        stu.getImmunizationmap().get("MMR").setDate(arrayMMR);
        stu.getImmunizationmap().get("Polio").setDate(arrayIPV);
        stu.getImmunizationmap().get("Varicella").setDate(arrayVAR);
        stu.getImmunizationmap().get("Meningococcal").setDate(arrayMeningococcal);
        stu.setRegisterState(true);
        System.out.println(stu.getFirstName());
        RatioRule.addStu(stu, dataStore);
        FileUtil.writeCsv();

        for (Student s : dataStore.getStuList()) {
            System.out.println(s);
        }

        String success = "Register Successsfully,Arrange to group" + stu.getGroupID();
        JOptionPane.showMessageDialog(null, success);
        toStudentInfoScreen();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtMein1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMein1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtMein1ActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtDTap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDTap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDTap1ActionPerformed

    private void txtHepb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHepb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHepb1ActionPerformed

    private void txtIPV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPV3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPV3ActionPerformed

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void toStudentInfoScreen() {
        CardLayout layout = (CardLayout) this.userProcessContainer.getLayout();
        this.userProcessContainer.remove(this);
        Component[] comps = this.userProcessContainer.getComponents();
        for (Component comp : comps) {
            if (comp instanceof StudentManagementPanel) {
                StudentManagementPanel panel = (StudentManagementPanel) comp;
                panel.populate();
            }
        }
        layout.previous(userProcessContainer);
    }

    private int getMaxStuId(List<Student> list) {
        int maxID = list.get(list.size() - 1).getStuID();
        return maxID;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDTap1;
    private javax.swing.JTextField txtDTap2;
    private javax.swing.JTextField txtDTap3;
    private javax.swing.JTextField txtDTap4;
    private javax.swing.JTextField txtDTap5;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtHepb1;
    private javax.swing.JTextField txtHepb2;
    private javax.swing.JTextField txtHepb3;
    private javax.swing.JTextField txtHepb4;
    private javax.swing.JTextField txtHepb5;
    private javax.swing.JTextField txtHib1;
    private javax.swing.JTextField txtHib2;
    private javax.swing.JTextField txtHib3;
    private javax.swing.JTextField txtHib4;
    private javax.swing.JTextField txtHib5;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIPV1;
    private javax.swing.JTextField txtIPV2;
    private javax.swing.JTextField txtIPV3;
    private javax.swing.JTextField txtIPV4;
    private javax.swing.JTextField txtIPV5;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMMR1;
    private javax.swing.JTextField txtMMR2;
    private javax.swing.JTextField txtMMR3;
    private javax.swing.JTextField txtMMR4;
    private javax.swing.JTextField txtMMR5;
    private javax.swing.JTextField txtMein1;
    private javax.swing.JTextField txtMein2;
    private javax.swing.JTextField txtMein3;
    private javax.swing.JTextField txtMein4;
    private javax.swing.JTextField txtMein5;
    private javax.swing.JTextField txtPfname;
    private javax.swing.JTextField txtPlame;
    private javax.swing.JTextField txtPnumber;
    private javax.swing.JTextField txtVAR1;
    private javax.swing.JTextField txtVAR2;
    private javax.swing.JTextField txtVAR3;
    private javax.swing.JTextField txtVAR4;
    private javax.swing.JTextField txtVAR5;
    private javax.swing.JTextField txtbirthday;
    // End of variables declaration//GEN-END:variables
}
